-- Shared ledger budget migration. Apply after multi_account_update.sql.
begin;

create table if not exists public."LedgerSavingsAccounts" (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 100),
  revision bigint not null default 1
);
insert into public."LedgerSavingsAccounts"(id,name)
values (1,'Primary Savings') on conflict (id) do nothing;
create unique index if not exists ledger_savings_account_name
  on public."LedgerSavingsAccounts"(lower(trim(name)));
select setval(pg_get_serial_sequence('public."LedgerSavingsAccounts"','id'),
  greatest(1,(select max(id) from public."LedgerSavingsAccounts")));

alter table public."LedgerSavingsBuckets" add column if not exists savings_account_id bigint
  not null default 1 references public."LedgerSavingsAccounts"(id);
drop index if exists public.ledger_savings_name;
drop index if exists public.ledger_savings_general;
create unique index ledger_savings_name on public."LedgerSavingsBuckets"
  (savings_account_id,lower(trim(name)));
create unique index ledger_savings_general on public."LedgerSavingsBuckets"
  (savings_account_id) where is_general;

alter table public."LedgerSavingsAccounts" enable row level security;
revoke all on public."LedgerSavingsAccounts" from public,anon,authenticated;
grant select on public."LedgerSavingsAccounts" to authenticated;
drop policy if exists ledger_savings_accounts_owner on public."LedgerSavingsAccounts";
create policy ledger_savings_accounts_owner on public."LedgerSavingsAccounts"
  for select to authenticated
  using ((select auth.uid())='5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid);
revoke all on sequence public."LedgerSavingsAccounts_id_seq" from public,anon,authenticated;

create or replace function public.ledger_create_savings_account(p_name text)
returns boolean language plpgsql security definer set search_path='' as $$
declare account_id bigint;
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  if p_name is null or length(trim(p_name)) not between 1 and 100
     or lower(trim(p_name)) in ('budget','reconcile','lines of credit','view / edit budget','amz card ledger')
    then raise exception 'Enter an account name'; end if;
  perform pg_catalog.pg_advisory_xact_lock(9282026);
  if exists(select 1 from public."LedgerCashAccounts"
            where lower(trim(name))=lower(trim(p_name)))
    then raise exception 'An account already has that name'; end if;
  insert into public."LedgerSavingsAccounts"(name) values(trim(p_name))
    returning id into account_id;
  insert into public."LedgerSavingsBuckets"
    (name,is_general,active,balance,savings_account_id)
    values ('General savings',true,true,0,account_id);
  return true;
end $$;
revoke all on function public.ledger_create_savings_account(text)
  from public,anon,authenticated;
grant execute on function public.ledger_create_savings_account(text) to authenticated;

create or replace function public.ledger_save_cash_account(p_name text)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  if p_name is null or length(trim(p_name)) not between 1 and 100
     or lower(trim(p_name)) in ('budget','reconcile','lines of credit','view / edit budget','amz card ledger')
     or exists(select 1 from public."LedgerSavingsAccounts"
       where lower(trim(name))=lower(trim(p_name)))
    then raise exception 'Choose a distinct checking account name'; end if;
  insert into public."LedgerCashAccounts"(name) values(trim(p_name));
  return true;
end $$;

create or replace function public.ledger_save_savings_bucket(
  p_id bigint,p_revision bigint,p_name text,p_active boolean,p_account bigint)
returns boolean language plpgsql security definer set search_path='' as $$
declare b public."LedgerSavingsBuckets"%rowtype; target bigint;
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  perform pg_catalog.pg_advisory_xact_lock(9282026);
  if p_name is null or length(trim(p_name)) not between 1 and 100 or p_active is null
    then raise exception 'Enter a category name'; end if;
  if not exists(select 1 from public."LedgerSavingsAccounts" where id=p_account)
    then raise exception 'Choose a savings account'; end if;
  if p_id is null then
    insert into public."LedgerSavingsBuckets"(name,active,savings_account_id)
      values(trim(p_name),p_active,p_account) returning id into target;
  else
    select * into strict b from public."LedgerSavingsBuckets" where id=p_id for update;
    if b.savings_account_id<>p_account or b.revision is distinct from p_revision
      then raise exception 'Savings category changed. Reload.'; end if;
    if b.is_general and (trim(p_name)<>'General savings' or not p_active)
      then raise exception 'General savings must remain active'; end if;
    if not p_active and coalesce(b.balance,0)<>0
      then raise exception 'Move the category balance before archiving'; end if;
    update public."LedgerSavingsBuckets"
      set name=trim(p_name),active=p_active,revision=revision+1 where id=p_id;
    target:=p_id;
  end if;
  insert into public."LedgerSavingsAudit"
    (operation_id,bucket_id,kind,delta,before_balance,after_balance,note,details,actor)
  select gen_random_uuid(),id,'Category',0,b.balance,balance,
    'Category created or changed',
    jsonb_build_object('before',to_jsonb(b),'name',name,'active',active),auth.uid()
  from public."LedgerSavingsBuckets" where id=target;
  return true;
end $$;
revoke all on function public.ledger_save_savings_bucket(bigint,bigint,text,boolean,bigint)
  from public,anon,authenticated;
grant execute on function public.ledger_save_savings_bucket(bigint,bigint,text,boolean,bigint)
  to authenticated;

-- Prevent cross-account allocations, including calls through the preexisting RPC.
create or replace function public.ledger_savings_account_guard()
returns trigger language plpgsql set search_path='' as $$
declare source_account bigint; destination_account bigint;
begin
  if new.kind='Allocation' then
    select savings_account_id into source_account
      from public."LedgerSavingsBuckets" where id=new.bucket_id;
    if new.details ? 'to' then
      select savings_account_id into destination_account
        from public."LedgerSavingsBuckets" where id=(new.details->>'to')::bigint;
    elsif new.details ? 'from' then
      select savings_account_id into destination_account
        from public."LedgerSavingsBuckets" where id=(new.details->>'from')::bigint;
    end if;
    if source_account is distinct from destination_account
      then raise exception 'Move money within one savings account only'; end if;
  end if;
  return new;
end $$;
drop trigger if exists ledger_savings_account_guard on public."LedgerSavingsAudit";
create trigger ledger_savings_account_guard before insert on public."LedgerSavingsAudit"
  for each row execute function public.ledger_savings_account_guard();
revoke all on function public.ledger_savings_account_guard() from public,anon,authenticated;

-- One shared set of expense rules. Editing a rule creates a dated version.
-- Individual occurrences keep their original scheduled date, even when the
-- actual transaction date is changed later.
create table if not exists public."LedgerUnifiedBudgetRules" (
  id bigint generated always as identity primary key,
  series_id uuid not null,
  previous_budget_rule text unique references public."LedgerBudgetRules"(id),
  effective_from date not null,
  effective_until date,
  name text not null check(length(trim(name)) between 1 and 200),
  description text not null default '',
  transaction_type text not null check(transaction_type in ('AMZ Card','Direct','Check','Transfer')),
  paid_from text not null,
  paid_to text not null,
  schedule text not null check(schedule in ('Monthly','Weekly','As needed')),
  day_of_month integer check(day_of_month between 1 and 31),
  weekday integer check(weekday between 0 and 6),
  amount numeric(14,2) not null check(amount>=0 and amount<1000000000),
  enabled boolean not null default true,
  revision bigint not null default 1,
  check(effective_until is null or effective_until>=effective_from),
  check((schedule='Weekly' and weekday is not null and day_of_month is null)
     or (schedule<>'Weekly' and weekday is null and day_of_month is not null))
);
create index if not exists ledger_unified_rule_series
  on public."LedgerUnifiedBudgetRules"(series_id,effective_from);

create table if not exists public."LedgerUnifiedBudgetOccurrences" (
  id bigint generated always as identity primary key,
  rule_id bigint not null references public."LedgerUnifiedBudgetRules"(id),
  scheduled_date date not null,
  actual_date date not null,
  amount numeric(14,2) not null check(amount>=0 and amount<1000000000),
  name text not null,
  description text not null default '',
  transaction_type text not null,
  paid_from text not null,
  paid_to text not null,
  modified boolean not null default false,
  cancelled boolean not null default false,
  transaction_id bigint unique references public."Transactions"(id) on delete set null,
  transfer_id bigint unique references public."LedgerTransfers"(id) on delete set null,
  revision bigint not null default 1,
  unique(rule_id,scheduled_date)
);
alter table public."Transactions" add column if not exists unified_occurrence_id bigint
  unique references public."LedgerUnifiedBudgetOccurrences"(id) on delete set null;
alter table public."LedgerTransfers" add column if not exists unified_occurrence_id bigint
  unique references public."LedgerUnifiedBudgetOccurrences"(id) on delete set null;

do $$ declare tab text; begin
  foreach tab in array array['LedgerUnifiedBudgetRules','LedgerUnifiedBudgetOccurrences'] loop
    execute format('alter table public.%I enable row level security',tab);
    execute format('revoke all on public.%I from public,anon,authenticated',tab);
    execute format('grant select on public.%I to authenticated',tab);
    execute format('drop policy if exists ledger_owner on public.%I',tab);
    execute format('create policy ledger_owner on public.%I for select to authenticated using ((select auth.uid())=%L::uuid)',
      tab,'5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d');
  end loop;
end $$;
revoke all on sequence public."LedgerUnifiedBudgetRules_id_seq",
  public."LedgerUnifiedBudgetOccurrences_id_seq" from public,anon,authenticated;

create or replace function public.ledger_unified_endpoint(p_ref text)
returns table(checking_id bigint,savings_bucket_id bigint)
language plpgsql security definer set search_path='' as $$
declare account_id bigint;
begin
  if p_ref ~ '^c:[0-9]+$' then
    checking_id:=substring(p_ref from 3)::bigint;
    if not exists(select 1 from public."LedgerCashAccounts" where id=checking_id)
      then raise exception 'Choose an existing checking account'; end if;
    savings_bucket_id:=null;
  elsif p_ref ~ '^s:[0-9]+$' then
    account_id:=substring(p_ref from 3)::bigint;
    select b.id into strict savings_bucket_id
      from public."LedgerSavingsBuckets" b
      where b.savings_account_id=account_id and b.is_general and b.active;
    checking_id:=null;
  else
    raise exception 'Choose an existing account';
  end if;
  return next;
end $$;
revoke all on function public.ledger_unified_endpoint(text) from public,anon,authenticated;

create table if not exists public."LedgerUnifiedPayees" (
  id bigint generated always as identity primary key,
  transaction_type text not null check(transaction_type in ('AMZ Card','Direct','Check')),
  label text not null check(length(trim(label)) between 1 and 100),
  unique(transaction_type,label)
);
insert into public."LedgerUnifiedPayees"(transaction_type,label)
values ('AMZ Card','Merchant'),('Direct','Merchant'),('Check','Merchant')
on conflict do nothing;
alter table public."LedgerUnifiedPayees" enable row level security;
revoke all on public."LedgerUnifiedPayees" from public,anon,authenticated;
grant select on public."LedgerUnifiedPayees" to authenticated;
drop policy if exists ledger_unified_payees_owner on public."LedgerUnifiedPayees";
create policy ledger_unified_payees_owner on public."LedgerUnifiedPayees"
  for select to authenticated
  using ((select auth.uid())='5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid);
revoke all on sequence public."LedgerUnifiedPayees_id_seq" from public,anon,authenticated;
create or replace function public.ledger_add_unified_payee(p_type text,p_label text)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  if p_type not in ('AMZ Card','Direct','Check') or p_label is null
     or length(trim(p_label)) not between 1 and 100
    then raise exception 'Choose a transaction type and a value'; end if;
  insert into public."LedgerUnifiedPayees"(transaction_type,label)
    values(p_type,trim(p_label));
  return true;
end $$;
revoke all on function public.ledger_add_unified_payee(text,text) from public,anon,authenticated;
grant execute on function public.ledger_add_unified_payee(text,text) to authenticated;

-- Move existing expense definitions into the shared editor at the cutover date.
-- Historical budget items and recorded transactions remain untouched.
create table if not exists public."LedgerUnifiedConfig" (
  id integer primary key check(id=1), cutover_date date not null
);
insert into public."LedgerUnifiedConfig"(id,cutover_date)
  values(1,(now() at time zone 'America/New_York')::date)
  on conflict(id) do nothing;
alter table public."LedgerUnifiedConfig" enable row level security;
revoke all on public."LedgerUnifiedConfig" from public,anon,authenticated;
grant select on public."LedgerUnifiedConfig" to authenticated;
drop policy if exists ledger_unified_config_owner on public."LedgerUnifiedConfig";
create policy ledger_unified_config_owner on public."LedgerUnifiedConfig"
  for select to authenticated
  using ((select auth.uid())='5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid);
insert into public."LedgerUnifiedBudgetRules"
  (series_id,previous_budget_rule,effective_from,name,description,transaction_type,
   paid_from,paid_to,schedule,day_of_month,amount,enabled)
select gen_random_uuid(),r.id,(select cutover_date from public."LedgerUnifiedConfig" where id=1),
  r.name,r.description,'Direct','c:'||r.cash_account_id,'Merchant',
  case when r.schedule='as_needed' then 'As needed' else 'Monthly' end,
  r.due_day,r.amount,false
from public."LedgerBudgetRules" r
where r.direction='Expense'
on conflict(previous_budget_rule) do nothing;

-- The old weekly funding definitions are deliberately left in the database
-- for history, but the new app never generates or displays them.

create or replace function public.ledger_save_unified_budget_rule(
  p_id bigint,p_revision bigint,p_effective_from date,p_data jsonb)
returns boolean language plpgsql security definer set search_path='' as $$
declare old_rule public."LedgerUnifiedBudgetRules"%rowtype;
  source_checking bigint; source_savings bigint;
  target_checking bigint; target_savings bigint;
  a public."LedgerUnifiedBudgetOccurrences"%rowtype;
  existing_transfer public."LedgerTransfers"%rowtype;
  v_name text; v_description text; v_type text; v_source text; v_target text;
  v_schedule text; v_day integer; v_weekday integer; v_amount numeric; v_enabled boolean;
  v_series uuid;
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  perform pg_catalog.pg_advisory_xact_lock(9282026);
  if p_data is null or jsonb_typeof(p_data)<>'object' or p_effective_from is null
    then raise exception 'Enter budget details'; end if;
  v_name:=trim(p_data->>'name');
  v_description:=coalesce(p_data->>'description','');
  v_type:=p_data->>'transaction_type';
  v_source:=p_data->>'paid_from';
  v_target:=p_data->>'paid_to';
  v_schedule:=p_data->>'schedule';
  v_day:=(p_data->>'day_of_month')::integer;
  v_weekday:=(p_data->>'weekday')::integer;
  v_amount:=(p_data->>'amount')::numeric;
  v_enabled:=(p_data->>'enabled')::boolean;
  if v_name is null or length(v_name) not between 1 and 200
    or v_type not in ('AMZ Card','Direct','Check','Transfer')
    or v_schedule not in ('Monthly','Weekly','As needed')
    or v_amount is null or v_amount<0 or v_amount>=1000000000
    or v_enabled is null or
    (v_schedule='Weekly' and (v_weekday is null or v_weekday not between 0 and 6 or v_day is not null))
    or (v_schedule<>'Weekly' and (v_day is null or v_day not between 1 and 31 or v_weekday is not null))
    then raise exception 'Invalid budget details'; end if;
  select checking_id,savings_bucket_id into source_checking,source_savings
    from public.ledger_unified_endpoint(v_source);
  if v_type='Transfer' then
    select checking_id,savings_bucket_id into target_checking,target_savings
      from public.ledger_unified_endpoint(v_target);
    if v_source=v_target then raise exception 'Choose different transfer accounts'; end if;
    if v_amount<=0 then raise exception 'Transfer amount must be positive'; end if;
  elsif not exists(select 1 from public."LedgerUnifiedPayees"
    where transaction_type=v_type and label=v_target) then
    raise exception 'Choose a listed Paid to value for this transaction type';
  end if;
  if v_type='AMZ Card' and v_source<>'c:1'
    then raise exception 'AMZ Card purchases must be paid from Primary Checking'; end if;

  if p_id is null then
    v_series:=gen_random_uuid();
    insert into public."LedgerUnifiedBudgetRules"
      (series_id,effective_from,name,description,transaction_type,paid_from,paid_to,
       schedule,day_of_month,weekday,amount,enabled)
    values(v_series,p_effective_from,v_name,v_description,v_type,v_source,v_target,
       v_schedule,v_day,v_weekday,v_amount,v_enabled);
    return true;
  end if;

  select * into strict old_rule from public."LedgerUnifiedBudgetRules"
    where id=p_id for update;
  if old_rule.revision is distinct from p_revision
    then raise exception 'Budget changed. Reload.'; end if;
  if old_rule.effective_until is not null
    then raise exception 'Choose the current budget version'; end if;
  if p_effective_from<(now() at time zone 'America/New_York')::date+
       (case when not old_rule.enabled and not exists(
         select 1 from public."LedgerUnifiedBudgetOccurrences" where rule_id=p_id)
         then 0 else 1 end)
     or p_effective_from<old_rule.effective_from
    then raise exception 'Changes to a recurring item begin with a future occurrence'; end if;

  for a in select * from public."LedgerUnifiedBudgetOccurrences"
     where rule_id=p_id and scheduled_date>=p_effective_from
       and not modified and not cancelled order by id for update loop
    if a.transaction_id is not null then
      if a.transaction_type='AMZ Card' and exists(
        select 1 from public."LedgerCardWeeks" w
        join public."Transactions" t on t.card_budget_week=w.week_ending
        where t.id=a.transaction_id)
        then raise exception 'A future card week is reconciled; leave its entries unchanged'; end if;
      delete from public."Transactions" where id=a.transaction_id;
    elsif a.transfer_id is not null then
      select * into strict existing_transfer from public."LedgerTransfers"
        where id=a.transfer_id;
      perform public.ledger_save_transfer(
        a.transfer_id,existing_transfer.revision,'{}'::jsonb,true);
    elsif a.paid_from like 's:%' then
      select savings_bucket_id into source_savings
        from public.ledger_unified_endpoint(a.paid_from);
      perform public.ledger_savings_apply(source_savings,a.amount,
        'Budget correction','Future budget item changed',null,gen_random_uuid(),
        jsonb_build_object('occurrence',a.id));
    end if;
    delete from public."LedgerUnifiedBudgetOccurrences" where id=a.id;
  end loop;

  if p_effective_from=old_rule.effective_from then
    update public."LedgerUnifiedBudgetRules" set name=v_name,description=v_description,
      transaction_type=v_type,paid_from=v_source,paid_to=v_target,
      schedule=v_schedule,day_of_month=v_day,weekday=v_weekday,
      amount=v_amount,enabled=v_enabled,revision=revision+1 where id=p_id;
  else
    update public."LedgerUnifiedBudgetRules"
      set effective_until=p_effective_from-1,revision=revision+1 where id=p_id;
    insert into public."LedgerUnifiedBudgetRules"
      (series_id,effective_from,name,description,transaction_type,paid_from,paid_to,
       schedule,day_of_month,weekday,amount,enabled)
    values(old_rule.series_id,p_effective_from,v_name,v_description,v_type,v_source,v_target,
       v_schedule,v_day,v_weekday,v_amount,v_enabled);
  end if;
  return true;
end $$;
revoke all on function public.ledger_save_unified_budget_rule(bigint,bigint,date,jsonb)
  from public,anon,authenticated;
grant execute on function public.ledger_save_unified_budget_rule(bigint,bigint,date,jsonb)
  to authenticated;

create or replace function public.ledger_prepare_unified_budget_month(p_month date)
returns boolean language plpgsql security definer set search_path='' as $$
declare r public."LedgerUnifiedBudgetRules"%rowtype;
  d date; last_day date; begin_day date; finish_day date;
  a public."LedgerUnifiedBudgetOccurrences"%rowtype;
  source_checking bigint; source_savings bigint;
  target_checking bigint; target_savings bigint;
  new_transaction bigint; new_transfer bigint; tx_data jsonb;
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  if p_month is null or extract(day from p_month)<>1
    then raise exception 'Choose the first day of a month'; end if;
  perform pg_catalog.pg_advisory_xact_lock(9282026);
  last_day:=(p_month+interval '1 month'-interval '1 day')::date;
  for r in select * from public."LedgerUnifiedBudgetRules"
    where enabled and effective_from<=last_day
      and (effective_until is null or effective_until>=p_month)
    order by id loop
    begin_day:=greatest(p_month,r.effective_from);
    finish_day:=least(last_day,coalesce(r.effective_until,last_day));
    for d in select generate_series(begin_day,finish_day,interval '1 day')::date loop
      if (r.schedule='Weekly' and extract(isodow from d)::integer-1=r.weekday)
        or (r.schedule<>'Weekly' and extract(day from d)::integer=
            least(r.day_of_month,extract(day from last_day)::integer)) then
        insert into public."LedgerUnifiedBudgetOccurrences"
          (rule_id,scheduled_date,actual_date,amount,name,description,
           transaction_type,paid_from,paid_to)
        values(r.id,d,d,r.amount,r.name,r.description,r.transaction_type,
               r.paid_from,r.paid_to)
        on conflict(rule_id,scheduled_date) do nothing returning * into a;
        if not found then continue; end if;
        select checking_id,savings_bucket_id into source_checking,source_savings
          from public.ledger_unified_endpoint(r.paid_from);
        if r.transaction_type='Transfer' then
          select checking_id,savings_bucket_id into target_checking,target_savings
            from public.ledger_unified_endpoint(r.paid_to);
          tx_data:=jsonb_build_object(
            'source_account',source_checking,'source_bucket',source_savings,
            'destination_account',target_checking,'destination_bucket',target_savings,
            'amount',r.amount,'date',d,'description',r.name,
            'schedule_id',null,'occurrence_date',null);
          perform public.ledger_save_transfer(null,null,tx_data,false);
          new_transfer:=currval(pg_get_serial_sequence('public."LedgerTransfers"','id'));
          update public."LedgerTransfers" set unified_occurrence_id=a.id
            where id=new_transfer;
          update public."LedgerUnifiedBudgetOccurrences" set transfer_id=new_transfer
            where id=a.id;
        elsif source_checking is not null then
          insert into public."Transactions"
            (date,time,type,direction,amount,merchant,category,description,
             cash_account_id,unified_occurrence_id)
          values(d,'12:00:00',r.transaction_type,'Expense',r.amount,r.name,
            'Budget',r.description,source_checking,a.id)
          returning id into new_transaction;
          update public."LedgerUnifiedBudgetOccurrences"
            set transaction_id=new_transaction where id=a.id;
        else
          perform public.ledger_savings_apply(source_savings,-r.amount,
            'Budget expense',r.name,null,gen_random_uuid(),
            jsonb_build_object('occurrence',a.id,'date',d,'type',r.transaction_type));
        end if;
      end if;
    end loop;
  end loop;
  return true;
end $$;
revoke all on function public.ledger_prepare_unified_budget_month(date)
  from public,anon,authenticated;
grant execute on function public.ledger_prepare_unified_budget_month(date)
  to authenticated;

-- Keep the one-off calendar and AMZ Ledger editors attached to their rule.
create or replace function public.ledger_track_unified_transaction()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if old.unified_occurrence_id is null then
    if TG_OP='DELETE' then return old; else return new; end if;
  end if;
  if TG_OP='DELETE' then
    update public."LedgerUnifiedBudgetOccurrences"
      set cancelled=true,modified=true,transaction_id=null,revision=revision+1
      where id=old.unified_occurrence_id;
    return old;
  end if;
  if row(new.date,new.amount,new.type,new.merchant,new.description,new.cash_account_id)
     is distinct from
     row(old.date,old.amount,old.type,old.merchant,old.description,old.cash_account_id) then
    update public."LedgerUnifiedBudgetOccurrences"
      set actual_date=new.date,amount=new.amount,name=new.merchant,
        description=coalesce(new.description,''),modified=true,revision=revision+1
      where id=old.unified_occurrence_id;
  end if;
  return new;
end $$;
create or replace function public.ledger_guard_unified_transaction()
returns trigger language plpgsql set search_path='' as $$
begin
  if old.unified_occurrence_id is not null and
     row(new.type,new.direction,new.cash_account_id,new.unified_occurrence_id)
     is distinct from
     row(old.type,old.direction,old.cash_account_id,old.unified_occurrence_id)
    then raise exception 'A budget occurrence may change amount, date or description only';
  end if;
  return new;
end $$;
drop trigger if exists ledger_guard_unified_transaction on public."Transactions";
create trigger ledger_guard_unified_transaction before update on public."Transactions"
  for each row execute function public.ledger_guard_unified_transaction();
revoke all on function public.ledger_guard_unified_transaction() from public,anon,authenticated;
drop trigger if exists ledger_track_unified_transaction on public."Transactions";
create trigger ledger_track_unified_transaction after update or delete on public."Transactions"
  for each row execute function public.ledger_track_unified_transaction();
revoke all on function public.ledger_track_unified_transaction() from public,anon,authenticated;

create or replace function public.ledger_track_unified_transfer()
returns trigger language plpgsql security definer set search_path='' as $$
declare from_ref text; to_ref text;
begin
  if old.unified_occurrence_id is null then
    if TG_OP='DELETE' then return old; else return new; end if;
  end if;
  if TG_OP='DELETE' then
    update public."LedgerUnifiedBudgetOccurrences"
      set cancelled=true,modified=true,transfer_id=null,revision=revision+1
      where id=old.unified_occurrence_id;
    return old;
  end if;
  if row(new.date,new.amount,new.source_account,new.source_bucket,
         new.destination_account,new.destination_bucket,new.description)
     is distinct from
     row(old.date,old.amount,old.source_account,old.source_bucket,
         old.destination_account,old.destination_bucket,old.description) then
    if new.source_account is not null then
      from_ref:='c:'||new.source_account;
    else
      select 's:'||savings_account_id into from_ref
        from public."LedgerSavingsBuckets" where id=new.source_bucket;
    end if;
    if new.destination_account is not null then
      to_ref:='c:'||new.destination_account;
    else
      select 's:'||savings_account_id into to_ref
        from public."LedgerSavingsBuckets" where id=new.destination_bucket;
    end if;
    update public."LedgerUnifiedBudgetOccurrences"
      set actual_date=new.date,amount=new.amount,paid_from=from_ref,paid_to=to_ref,
        description=new.description,modified=true,revision=revision+1
      where id=old.unified_occurrence_id;
  end if;
  return new;
end $$;
drop trigger if exists ledger_track_unified_transfer on public."LedgerTransfers";
create trigger ledger_track_unified_transfer after update or delete on public."LedgerTransfers"
  for each row execute function public.ledger_track_unified_transfer();
revoke all on function public.ledger_track_unified_transfer() from public,anon,authenticated;

-- Budget-generated AMZ purchases belong to the week containing their actual
-- date. The existing historical/manual card allocation remains unchanged.
create or replace function public.ledger_assign_card_week() returns trigger
language plpgsql security definer set search_path='' as $$
declare latest date; target_week date;
begin
  if TG_OP<>'INSERT' and old.type='AMZ Card' and exists(
      select 1 from public."LedgerCardWeeks" where week_ending=old.card_budget_week) then
    if TG_OP='DELETE' then
      raise exception 'This card transaction belongs to a reconciled week and cannot be deleted';
    end if;
    if row(new.amount,new.direction,new.type,new.date,new.card_budget_week)
       is distinct from
       row(old.amount,old.direction,old.type,old.date,old.card_budget_week) then
      raise exception 'Amounts, direction, date and budget week are locked after reconciliation';
    end if;
  end if;
  if TG_OP='DELETE' then return old; end if;
  if new.type<>'AMZ Card' then
    new.card_budget_week:=null;
  elsif new.unified_occurrence_id is not null then
    target_week:=new.date+(5-extract(isodow from new.date)::integer+1+7)%7;
    if exists(select 1 from public."LedgerCardWeeks" where week_ending=target_week)
       and (TG_OP='INSERT' or new.date is distinct from old.date) then
      raise exception 'The target AMZ week is already reconciled';
    end if;
    new.card_budget_week:=target_week;
  elsif TG_OP='INSERT' or old.type is distinct from 'AMZ Card' then
    select max(week_ending) into latest from public."LedgerCardWeeks";
    new.card_budget_week:=coalesce(latest+7,new.date+(6-extract(dow from new.date)::integer));
  else
    new.card_budget_week:=old.card_budget_week;
  end if;
  return new;
end $$;

-- Savings-only expenses have no checking transaction row, so their one-off
-- editor uses this narrow RPC to reverse or adjust the corresponding bucket.
create or replace function public.ledger_edit_unified_savings_occurrence(
  p_id bigint,p_revision bigint,p_date date,p_amount numeric,p_delete boolean)
returns boolean language plpgsql security definer set search_path='' as $$
declare a public."LedgerUnifiedBudgetOccurrences"%rowtype;
  bucket_id bigint; adjustment numeric;
begin
  if auth.uid() is distinct from '5a9e2156-a5cb-4f65-9a7c-db8e0f92bf1d'::uuid
    then raise exception 'Not authorized'; end if;
  perform pg_catalog.pg_advisory_xact_lock(9282026);
  select * into strict a from public."LedgerUnifiedBudgetOccurrences"
    where id=p_id for update;
  if a.revision is distinct from p_revision
    then raise exception 'This occurrence changed. Reload.'; end if;
  if a.cancelled or a.transaction_id is not null or a.transfer_id is not null
     or a.transaction_type='Transfer' or a.paid_from not like 's:%'
    then raise exception 'Choose a savings expense occurrence'; end if;
  select savings_bucket_id into bucket_id from public.ledger_unified_endpoint(a.paid_from);
  if p_delete then
    adjustment:=a.amount;
    update public."LedgerUnifiedBudgetOccurrences"
      set cancelled=true,modified=true,revision=revision+1 where id=p_id;
  else
    if p_date is null or p_amount is null or p_amount<0 or p_amount>=1000000000
      then raise exception 'Enter a date and a valid amount'; end if;
    adjustment:=a.amount-round(p_amount,2);
    update public."LedgerUnifiedBudgetOccurrences"
      set actual_date=p_date,amount=round(p_amount,2),modified=true,revision=revision+1
      where id=p_id;
  end if;
  if adjustment<>0 then
    perform public.ledger_savings_apply(bucket_id,adjustment,
      'Budget correction','One-time savings budget edit',null,gen_random_uuid(),
      jsonb_build_object('occurrence',p_id,'deleted',p_delete));
  end if;
  return true;
end $$;
revoke all on function public.ledger_edit_unified_savings_occurrence(bigint,bigint,date,numeric,boolean)
  from public,anon,authenticated;
grant execute on function public.ledger_edit_unified_savings_occurrence(bigint,bigint,date,numeric,boolean)
  to authenticated;

commit;




